title: Amy Parent
email: amy@amyparent.com
timezone: Europe/London
permalink: /blog/:title/
author: Amy Parent

avatar: /static/media/amy.jpg
greeting: Hiya! I'm AmyÂ Parent.
description: >
  By day, I study cloud evolution in brown dwarfs at Abertay University. By night, I get bruises skating with DundeeÂ RollerÂ Derby, tell computers what to do and make video games ğŸ‘©ğŸ¼â€ğŸš€ğŸ‘©ğŸ¼â€ğŸ’»
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amyparent.com"
instagram_username: amyinorbit
twitter_username: amyinorbit
github_username:  amyinorbit
googleplus_uid:   116701126192141560817

# Build settings
markdown: kramdown
highlighter: rouge

# Pagination
# excerpt_separator: <!--more-->
# paginate: 8
# paginate_path: "/blog/:num"

plugins:
  - jekyll-feed
  - jekyll-redirect-from

include:
  - .htaccess

collections:
  papers:
    output: false

exclude:
  - vendor/bundle
  - Gemfile
  - Gemfile.lock
